### ISSUE TITLE
Problem: initialize error in metaverse demo

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-unreal-plugin#298]
PlayCppSdk InitializeWalletConnect Error: socket error: TLS error: webpki error: UnsupportedCriticalExtension
Getting from EnsureSession error: invalid client

**Comment by leejw51crypto** [comment]
trying to reproduce on windows

**Comment by elai950** [comment]
I did some digging and I've found something that might be related.
EnsureSession shows an Invalid client.

I noticed this warning while compiling:
```
'E:\Program Files\Epic Games\UE_5.1\Engine\Plugins\Marketplace\CronosPlay\Source\ThirdParty\PlayCppSdkLibrary\Lib\Win64\play_cpp_sdk.lib' does not exist
'E:\Program Files\Epic Games\UE_5.1\Engine\Source\Ncrypt.lib' does not exist.
'E:\Program Files\Epic Games\UE_5.1\Engine\Source\userenv.lib' does not exist.
'E:\Program Files\Epic Games\UE_5.1\Engine\Source\bcrypt.lib' does not exist.
'E:\Program Files\Epic Games\UE_5.1\Engine\Source\ntdll.lib' does not exist.
'E:\Program Files\Epic Games\UE_5.1\Engine\Source\Secur32.lib' does not exist.
'E:\Program Files\Epic Games\UE_5.1\Engine\Source\crypt32.lib' does not exist.
'E:\Program Files\Epic Games\UE_5.1\Engine\Source\ws2_32.lib' does not exist.
```

Check the file `PlayCppSdkLibrary.Build.cs`.

The first line which is `play_cpp_sdk.lib` is actually exactly where the address says he isn't (??).
All the rest really don't exist.
Tried to reinstall the plugin but that didn't work.

So in `PlayCppSdkLibrary.Build.cs`, you have a condition for Win64 platform type, and you're adding those files that one of them I have (but it says I don't) and all the others are missing so maybe that's related to why it's isn't working.

**Comment by leejw51crypto** [comment]
ok, i'll check on windows

**Comment by elai950** [comment]
Opened a new blank project and still had the same Invalid Client error.
Tried with UE 5.0 (using 5.1 as the main version) and installed the plugin fresh and still the same.

Windows 10 64-bit.
I'm trying to debug the code now.
Wish I could help somehow to solve that problem.

From what I understand when calling `ConnectWalletConnect` you call `RestoreClient` function so basically if the client is NULL this would be the error.
Didn't see you initiated `_client`, though I don't know Rust so I must be wrong.

**Comment by leejw51crypto** [comment]
thanks, i'm checking now

**Comment by damoncro** [comment]
It is working fine in my setting, what chain_id and rpc are you using?

**Comment by damoncro** [comment]
The error was generated by https://briansmith.org/rustdoc/webpki/enum.Error.html#variant.UnsupportedCriticalExtension that possibly originated from tokio-tungstenite, it seems it was generated when you connected to the chain that possibly has compatible issue.

**Comment by damoncro** [comment]
The error was generated by https://briansmith.org/rustdoc/webpki/enum.Error.html#variant.UnsupportedCriticalExtension that possibly originated from tokio-tungstenite, it seems it was generated when you connected to the chain that possibly has compatible issue.

**Comment by damoncro** [comment]
Please make sure the chain_id and rpc settings are correct:
https://github.com/cronos-labs/play-unreal-demo/blob/main/Metaverse/Source/Metaverse/Private/Components/WalletConnectTriggerComponent.cpp#L42
https://github.com/cronos-labs/play-unreal-demo/blob/main/Metaverse/Source/Metaverse/Private/Components/DefiWalletCoreComponent.cpp#L33-L34

**Comment by leejw51crypto** [comment]
i tested plugin version in marketplace and metaverse in github
, modified  metaverse uproject
```
{
			"Name": "CronosPlayUnreal",
			"Enabled": true
}
```

working fine.
can be os issue or visual studio ?
os: windows 11
visual studio: visual studio 2019

**Comment by leejw51crypto** [comment]
maybe update windows?

**Comment by elai950** [comment]
Windows 10 64 bit.
Rpc: https://evm-dev-t3.cronos.org/
Chain Id: 338

I'm able to get balance and transfer tokens using ERC20 functions so I really can't understand what's the problem with the connect wallet and qr code, the invalid client etc.

**Comment by damoncro** [comment]
Hi @elai950 
To make it simple first, would you able to download the demo project and test with it first?

https://github.com/cronos-labs/play-unreal-demo/releases/download/v0.0.9-alpha/CronosPlayMetaverseDemo.zip

Simply open the uproject then click play.

Would like to know if it is still the same.

**Comment by elai950** [comment]
> Hi @elai950 
> To make it simple first, would you able to download the demo project and test with it first?
> 
> https://github.com/cronos-labs/play-unreal-demo/releases/download/v0.0.9-alpha/CronosPlayMetaverseDemo.zip
> 
> Simply open the uproject then click play.
> 
> Would like to know if it is still the same.
> 

Yea that's what I did. Still the same error.

**Comment by elai950** [comment]
This is the logs

![צילום מסך 2023-04-11 171258](https://user-images.githubusercontent.com/37900883/231190759-eec383d0-4f70-4667-b5ac-a12c27cfcae4.png)

**Comment by leejw51crypto** [comment]
i reproducedf by setting time to incorrect one
```
wallet connect error=socket error: IO error: invalid peer certificate contents: invalid peer certificate: CertNotValidYet
```

but not the same error

**Comment by leejw51crypto** [comment]
i uploaded to test tls
https://github.com/leejw51crypto/play-cpp-sdk/tree/tls
- install rust
- window_build.bat
- cd demo\demo\x64\Release
- demo.exe

if it runs fine, unreal plugin will also work

**Comment by leejw51crypto** [comment]
window_build.bat will compile it.
you need cmake, visual studio 2019 installed beforehand.

i'm wondering whether  demo.exe  runs successfully

**Comment by leejw51crypto** [comment]
@elai950  ,  could you try with ssh first?
```
git clone https://github.com/leejw51crypto/play-cpp-sdk.git
```

if that works, we can assume that https working good

**Comment by elai950** [comment]
> * git clone [git@github.com](mailto:git@github.com):leejw51crypto/play-cpp-sdk.git

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

That's the error when trying to clone using ssh.

**Comment by leejw51crypto** [comment]
ok, just ssh issue

**Comment by leejw51crypto** [comment]
i'm checking again~

**Comment by leejw51crypto** [comment]
or just 
- open  x64 native tools command prompt for vs 2019
- run window_build.bat
- go the same folder above

**Comment by leejw51crypto** [comment]
yes, that's because git bring modules via ssh,
could you register your ssh for github?
then it will work

**Comment by leejw51crypto** [comment]
i will install fresh windows 11 and check again

**Comment by leejw51crypto** [comment]
i added code for test
- install rust on windows
- git clone https://github.com/leejw51crypto/play-cpp-sdk.git
- cd play-cpp-sdk
- git checkout tls
- cd test-tls
- cargo run

if https working fine , 
```
Running `target/debug/test-tls`
WebSocket connection established!
WebSocket connection closed.
```
this output will appear

**Comment by elai950** [comment]
> i added code for test
> 
> * install rust on windows
> * git clone https://github.com/leejw51crypto/play-cpp-sdk.git
> * cd play-cpp-sdk
> * git checkout tls
> * cd test-tls
> * cargo run
> 
> if https working fine , this will be printed
> 
> ```
> Running `target/debug/test-tls`
> WebSocket connection established!
> WebSocket connection closed.
> ```
> 
> this output will appear
> 
> @elai950 , it think this rust code would be simpler to test.

I got this:

```
PS C:\play-cpp-sdk\test-tls> cargo run
    Updating crates.io index
error: failed to get `defi-wallet-core-common` as a dependency of package `extra-cpp-bindings v0.1.0 (C:\play-cpp-sdk\extra-cpp-bindings)`

Caused by:
  failed to load source for dependency `defi-wallet-core-common`

Caused by:
  Unable to update C:\play-cpp-sdk\defi-wallet-core-rs\common

Caused by:
  failed to read `C:\play-cpp-sdk\defi-wallet-core-rs\common\Cargo.toml`

Caused by:
  The system cannot find the path specified. (os error 3)
```

But this is much simpler indeed.

**Comment by leejw51crypto** [comment]
thanks, i'll check more

**Comment by leejw51crypto** [comment]
try this one
- git clone https://github.com/leejw51crypto/CodingNote.git
- cd CodingNote/test-tls
- cargo run

**Comment by elai950** [comment]
Yes, it worked

```
WebSocket connection established!
WebSocket connection closed.
```

**Comment by leejw51crypto** [comment]
thanks, i can reduce the problem area

**Comment by leejw51crypto** [comment]
i replaced ssh with https, could you git clone again?   @elai950 
- git clone https://github.com/leejw51crypto/CodingNote.git
- cd CodingNote/test-tls
- cargo run

**Comment by leejw51crypto** [comment]
i replace ssh with https, could you retry again?
- git clone https://github.com/leejw51crypto/play-cpp-sdk.git
- cd play-cpp-sdk
- git checkout tls
- cd test-tls
- cargo run

i'm installing fresh windows 10, check too

> Used the Developer Command Prompt v17.5.3 VS 2022 I tried that but the build failed. That's the error and the command (the whole process).
> 
> Still, no demo.exe file exists.
> 
> ```
> C:\play-cpp-sdk\demo>msbuild .\demo.sln -t:rebuild -property:Configuration=Release /p:Platform=x64
> MSBuild version 17.5.1+f6fdcf537 for .NET Framework
> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
> Build started 13/04/2023 19:06:53.
> Included response file: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\MSBuild.rsp
> 
> Project "C:\play-cpp-sdk\demo\demo.sln" on node 1 (rebuild target(s)).
> ValidateSolutionConfiguration:
>   Building solution configuration "Release|x64".
> Project "C:\play-cpp-sdk\demo\demo.sln" (1) is building "C:\play-cpp-sdk\demo\demo\demo.vcxproj" (2) on node 1 (Rebuild
>  target(s)).
> PrepareForBuild:
>   Creating directory "x64\Release\demo.tlog\".
> InitializeBuildStatus:
>   Creating "x64\Release\demo.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> PreBuildEvent:
>   cd ..
>   call C:\play-cpp-sdk\demo\pre_build.bat
>   :VCEnd
>   Submodule 'defi-wallet-core-rs' (git@github.com:crypto-com/defi-wallet-core-rs.git) registered for path 'defi-wallet-
>   core-rs'
>   Submodule 'demo/third_party/easywsclient' (git@github.com:dhbaird/easywsclient.git) registered for path 'demo/third_p
>   arty/easywsclient'
>   Submodule 'demo/third_party/json' (git@github.com:nlohmann/json.git) registered for path 'demo/third_party/json'
>   Cloning into 'C:/play-cpp-sdk/defi-wallet-core-rs'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:crypto-com/defi-wallet-core-rs.git' into submodule path 'C:/play-cpp-sdk/defi-wallet-
>   core-rs' failed
>   Failed to clone 'defi-wallet-core-rs'. Retry scheduled
>   Cloning into 'C:/play-cpp-sdk/demo/third_party/easywsclient'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:dhbaird/easywsclient.git' into submodule path 'C:/play-cpp-sdk/demo/third_party/easyw
>   sclient' failed
>   Failed to clone 'demo/third_party/easywsclient'. Retry scheduled
>   Cloning into 'C:/play-cpp-sdk/demo/third_party/json'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:nlohmann/json.git' into submodule path 'C:/play-cpp-sdk/demo/third_party/json' failed
>   Failed to clone 'demo/third_party/json'. Retry scheduled
>   Cloning into 'C:/play-cpp-sdk/defi-wallet-core-rs'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:crypto-com/defi-wallet-core-rs.git' into submodule path 'C:/play-cpp-sdk/defi-wallet-
>   core-rs' failed
>   Failed to clone 'defi-wallet-core-rs' a second time, aborting
>   Traceback (most recent call last):
>     File "C:\play-cpp-sdk\demo\helper.py", line 218, in <module>
>       copy_example_files(".")
>     File "C:\play-cpp-sdk\demo\helper.py", line 145, in copy_example_files
>       shutil.copy(f, output_path)
>     File "C:\Python311\Lib\shutil.py", line 419, in copy
>       copyfile(src, dst, follow_symlinks=follow_symlinks)
>     File "C:\Python311\Lib\shutil.py", line 256, in copyfile
>       with open(src, 'rb') as fsrc:
>            ^^^^^^^^^^^^^^^
>   FileNotFoundError: [Errno 2] No such file or directory: '../defi-wallet-core-rs/example/cpp-example/chainmain.cc'
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: The command "cd .. [C:\play-cpp-sdk\demo\demo\demo.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: call C:\play-cpp-sdk\demo\pre_build.bat [C:\play-cpp-sdk\demo\demo\demo.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: :VCEnd" exited with code 1. [C:\play-cpp-sdk\demo\demo\demo.vcxproj]
> Done Building Project "C:\play-cpp-sdk\demo\demo\demo.vcxproj" (Rebuild target(s)) -- FAILED.
> 
> Project "C:\play-cpp-sdk\demo\demo.sln" (1) is building "C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj" (3) on nod
> e 1 (Rebuild target(s)).
> PrepareForBuild:
>   Creating directory "x64\Release\demostatic.tlog\".
> InitializeBuildStatus:
>   Creating "x64\Release\demostatic.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> PreBuildEvent:
>   cd ..
>   call C:\play-cpp-sdk\demo\pre_build.bat
>   :VCEnd
>   Cloning into 'C:/play-cpp-sdk/defi-wallet-core-rs'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:crypto-com/defi-wallet-core-rs.git' into submodule path 'C:/play-cpp-sdk/defi-wallet-
>   core-rs' failed
>   Failed to clone 'defi-wallet-core-rs'. Retry scheduled
>   Cloning into 'C:/play-cpp-sdk/demo/third_party/easywsclient'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:dhbaird/easywsclient.git' into submodule path 'C:/play-cpp-sdk/demo/third_party/easyw
>   sclient' failed
>   Failed to clone 'demo/third_party/easywsclient'. Retry scheduled
>   Cloning into 'C:/play-cpp-sdk/demo/third_party/json'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:nlohmann/json.git' into submodule path 'C:/play-cpp-sdk/demo/third_party/json' failed
>   Failed to clone 'demo/third_party/json'. Retry scheduled
>   Cloning into 'C:/play-cpp-sdk/defi-wallet-core-rs'...
>   git@github.com: Permission denied (publickey).
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
>   fatal: clone of 'git@github.com:crypto-com/defi-wallet-core-rs.git' into submodule path 'C:/play-cpp-sdk/defi-wallet-
>   core-rs' failed
>   Failed to clone 'defi-wallet-core-rs' a second time, aborting
>   Traceback (most recent call last):
>     File "C:\play-cpp-sdk\demo\helper.py", line 218, in <module>
>       copy_example_files(".")
>     File "C:\play-cpp-sdk\demo\helper.py", line 145, in copy_example_files
>       shutil.copy(f, output_path)
>     File "C:\Python311\Lib\shutil.py", line 419, in copy
>       copyfile(src, dst, follow_symlinks=follow_symlinks)
>     File "C:\Python311\Lib\shutil.py", line 256, in copyfile
>       with open(src, 'rb') as fsrc:
>            ^^^^^^^^^^^^^^^
>   FileNotFoundError: [Errno 2] No such file or directory: '../defi-wallet-core-rs/example/cpp-example/chainmain.cc'
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: The command "cd .. [C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: call C:\play-cpp-sdk\demo\pre_build.bat [C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: :VCEnd" exited with code 1. [C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj]
> Done Building Project "C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj" (Rebuild target(s)) -- FAILED.
> 
> Done Building Project "C:\play-cpp-sdk\demo\demo.sln" (rebuild target(s)) -- FAILED.
> 
> 
> Build FAILED.
> 
> "C:\play-cpp-sdk\demo\demo.sln" (rebuild target) (1) ->
> "C:\play-cpp-sdk\demo\demo\demo.vcxproj" (Rebuild target) (2) ->
> (PreBuildEvent target) ->
>   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5):
>  error MSB3073: The command "cd .. [C:\play-cpp-sdk\demo\demo\demo.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: call C:\play-cpp-sdk\demo\pre_build.bat [C:\play-cpp-sdk\demo\demo\demo.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: :VCEnd" exited with code 1. [C:\play-cpp-sdk\demo\demo\demo.vcxproj]
> 
> 
> "C:\play-cpp-sdk\demo\demo.sln" (rebuild target) (1) ->
> "C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj" (Rebuild target) (3) ->
>   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5):
>  error MSB3073: The command "cd .. [C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: call C:\play-cpp-sdk\demo\pre_build.bat [C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): e
> rror MSB3073: :VCEnd" exited with code 1. [C:\play-cpp-sdk\demo\demostatic\demostatic.vcxproj]
> 
>     0 Warning(s)
>     2 Error(s)
> ```

**Comment by leejw51crypto** [comment]
in windows 10, cannot reproduce.

can you run metaverse example ?
`ConnectWalletConnect` is suspicious

**Comment by leejw51crypto** [comment]
when calling ConnectWalletConnect,
- url:  set like `http://localhost:8080/`
- icon urls: empty , if any, it should be url like "http://..."
then i think, it will continue

**Comment by elai950** [comment]
Yea but for this URL I need to run a Hardhat node for example, am I right? And in the URL assign the hardhat port.
Can I use these settings? 
Rpc: https://evm-dev-t3.cronos.org/
Chain Id: 338

**Comment by leejw51crypto** [comment]
it should work, i'll check further.
it's connected via websocket
http-> ws
https-> wss

**Comment by leejw51crypto** [comment]
maybe setup like this?
![image](https://user-images.githubusercontent.com/51560997/232566312-dcd3bca1-60bc-4f4c-a003-d2db999bb63b.png)

**Comment by elai950** [comment]
![2023-04-17 20_39_41-Window](https://user-images.githubusercontent.com/37900883/232566629-2d47be01-beb3-41f0-ad85-0d37941b3d97.png)

Tried that, and also tried running localhost with a hardhat node but same result in all of them.
Every URL combination, every chain id 25 or 338 all was the same error.

**Comment by leejw51crypto** [comment]
how about url like http://localhost:8080/ ?

**Comment by elai950** [comment]
Yes, the same results.
Tried both localhost:8545 and 8080.

**Comment by leejw51crypto** [comment]
how about url  as  `http://127.0.0.1` ?
without port

**Comment by elai950** [comment]
Same results.
Tried just now.
Exactly the same settings.

**Comment by leejw51crypto** [comment]
i see,  seems by another reason.
i'll check further~

**Comment by leejw51crypto** [comment]
don't call ConnectWalletConnect first.
call InitializeWalletConnect first, then check true is displayed.
then connection is ok

**Comment by elai950** [comment]
I did all the tests on both Init and Connect just to be sure.

I think that first, we need to solve the session problem.
Because it won't connect if the session didn't create and the client is invalid (there's an if condition in the code if the client is invalid then throw that error).

**Comment by leejw51crypto** [comment]
yes, so it's like this
- InitializeWalletConnect
- GetQRCode or string, display
- EnsureSession
- Sign

**Comment by elai950** [comment]
Yes, I first call the InitializeWalletConnect.
But see this:

![2023-04-17 21_26_24-Window](https://user-images.githubusercontent.com/37900883/232577815-b84a37ed-c2de-418a-adc5-1ddc21926a56.png)

The last line, assert. if the client is invalid the whole process fails with that Invalid Client error which resulting UnsupportedCriticalExtension.

I might be wrong I'm not pretending to understand how the whole code works but from my understanding first, the client bug should be resolved.

**Comment by leejw51crypto** [comment]
yes, it should work. strange

i'll do the same today to reproduce
- InitializeWalletConnect
- ConnectWalletConnect

**Comment by leejw51crypto** [comment]
![image](https://user-images.githubusercontent.com/51560997/232637173-12964a6c-9833-478c-aa6d-cf67e829d8b7.png)

**Comment by leejw51crypto** [comment]
reproduced
![image](https://user-images.githubusercontent.com/51560997/232637344-23fe3306-f4fb-45ea-a5f1-d2adc6477228.png)

i will keep looking

**Comment by leejw51crypto** [comment]
![image](https://user-images.githubusercontent.com/51560997/232637423-b285b19a-727e-4418-95e8-b1a5051d7390.png)

**Comment by leejw51crypto** [comment]
![image](https://user-images.githubusercontent.com/51560997/232640210-4741e107-f9d9-4e3b-b55c-bbeb3b604604.png)

**Comment by leejw51crypto** [comment]
flow is
- InitialzeWalletConnect
- show qr or connection string
- ensure session <- wait until user approves pairing

**Comment by leejw51crypto** [comment]
i'm checking ConnectWalletConnect now

**Comment by elai950** [comment]
I'm failing in the callback of InitializeWalletConnect with success == false.
With the error we mentioned.

**Comment by leejw51crypto** [comment]
i see, i'll check further

**Comment by leejw51crypto** [comment]
@elai950  could you check one more test?
- open windows terminal
- git clone https://github.com/leejw51crypto/CodingNote.git
- cd CodingNote\test-walletconnect
- run.bat  or (cargo run --example web3)
- if qrcode displayed, unreal will also work

**Comment by leejw51crypto** [comment]
found similar issue: https://github.com/snapview/tokio-tungstenite/issues/231

**Comment by leejw51crypto** [comment]
changed root certificate type 
ref: https://github.com/cronos-labs/play-cpp-sdk/pull/433

**Comment by leejw51crypto** [comment]
thanks, for testing
i assume it's by tokio-tungstenite certificate handling
https://github.com/cronos-labs/play-cpp-sdk/pull/433

after this pr, merged, we will ship to our next plugin release

**Comment by elai950** [comment]
Hey guys,
Just updating don't know if it helps or if you managed to find and solve the problem.
I got a new PC today brand new, with a fresh Windows 11 64-bit.
This problem is still reproduced.

**Comment by damoncro** [comment]
I noticed @leejw51crypto posted a new [commit](https://github.com/cronos-labs/play-cpp-sdk/commit/de494f6d92d0bdd4d42907c03926fbc156748ab0) on play-cpp-sdk which is the library that used in play-unreal-plugin. I guess, it possibly fixed the issue. But we haven't brought it to play-unreal-unreal, but likely be release at next version (v0.0.20-alpha).

Would you @elai950  like to try it out?
Kindly follow the step in https://github.com/cronos-labs/play-cpp-sdk#windows-1

It builds alongs wallet_connect.exe example which initialises the wallet_connect and print the QR code.
Check the CI action here: https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4783717180/jobs/8504308181#step:9:229

Kindly know that please install python and msvc, you can check how we build in CI: https://github.com/cronos-labs/play-cpp-sdk/blob/main/.github/workflows/win-build.yml

Once QR is shown, the problem should be fixed.

**Comment by elai950** [comment]
Hey guys,
Any news about this issue? still getting the error btw.

**Comment by damoncro** [comment]
Walletconnect 1.0 is about to sunset, @leejw51crypto is working on walletconnect 2.0. You can try once it is ready.
